NewsAPI-Implementation/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Mvc;
using NewsAPI.Models;

namespace NewsAPI_Implementation.Controllers
{
    public class ArticleController : Controller
    { 
        public IActionResult ExpandedArticle(Article art)
        {

            return View(art);
        }
    }
}

NewsAPI-Implementation/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using NewsAPI_Implementation.Data;
using NewsAPI_Implementation.Models;
using NewsAPI_Implementation.Data;

namespace NewsAPI_Implementation.Controllers
{
    public class UserController : Controller
    {

        //TODO: ADD CARD PAYMENT OR MERCADOPAGO TO CHANGE ISPREMIUM VALUE
        private MyDbContext _context;
        private CommonMethods _commonMethods;
        public UserController (MyDbContext context)
        {
            _context = context;
            _commonMethods = new CommonMethods(context);
        }

        [HttpPost]
        public ActionResult RegisterUser(string user, string email, string pass)
        {

            User newUser = new User(user, pass, email);
            newUser.HashPassword();

            _context.Users.Add(newUser);
            _context.SaveChanges();
            return View();
        }

        [HttpPost]
        public ActionResult LoginUser(string user, string pass)
        {
            User? searchUser = _commonMethods.GetUser(user);
            if (searchUser != null)
            {
                if(BCrypt.Net.BCrypt.Verify(pass, searchUser.Password))
                {
                    HttpContext.Session.SetString("Username", searchUser.Username);
                    HttpContext.Session.SetInt32("PreferedLanguage", (int)searchUser.PreferedLanguage);
                    HttpContext.Session.Set("IsPremium", BitConverter.GetBytes(searchUser.IsPremium));
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return View("Login");
                }
            }
            else
            {
                return View("Login");
            }
        }

        public ActionResult Login()
        {
            return View();
        }

        public ActionResult LogOut()
        {
            HttpContext.Session.Remove("Username");
            HttpContext.Session.Remove("IsPremium");
            return View("Login");
        }
    }
}

NewsAPI-Implementation/Views/Shared/_Article.cshtml
@using NewsAPI.Models;
@model Article
@inject IHttpContextAccessor HttpContextAccessor

<link rel="stylesheet" href="~/css/Articles.css" />
@{
    var username = HttpContextAccessor.HttpContext.Session.GetString("Username");
    var sourceId = Model.Source.Id;
}
@if(username != null)
{
    if(sourceId != null)
    {
        <i class="fa fa-heart empty-heart" id="heart-@sourceId"></i>
    }
}
<a href="@Url.Action("ExpandedArticle", "Article", new { art = Model })">
    <div class="card">
        <img src="@Model.UrlToImage" />
        <h3>@Model.Title</h3>
        <p>@Model.Description</p>
        <p>@Model.PublishedAt</p>
    </div>
</a>

<script>
    (function() {
      const heart = document.getElementById(`heart-${@sourceId}`);
      heart.addEventListener('click', function() {
          $(`#heart-${@sourceId}`).css('color', 'red');
      });
    })();

</script>

NewsAPI-Implementation/Views/Shared/_Layout.cshtml
@using NewsAPI.Constants;
@using Microsoft.AspNetCore.Mvc;
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
@{
    var username = HttpContextAccessor.HttpContext.Session.GetString("Username");
    var isPremiumBytes = HttpContextAccessor.HttpContext.Session.Get("IsPremium");
    var isPremium = isPremiumBytes != null ? BitConverter.ToBoolean(isPremiumBytes, 0) : false;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - News For You</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NewsAPI_Implementation.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Articles.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NewsAPI_Implementation</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if(username != null)
                        {
                            if(!isPremium)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark btn btn-success" asp-area="" asp-controller="Home" asp-action="GetPremium">Get Premium!</a>
                                </li>
                            }
                            <form id="language-form" method="post" style="display:flex;">
                                <li class="nav-item">
                                    @Html.DropDownList("Languages",
                                    Html.GetEnumSelectList<Languages>(),
                                    "Select Language",new { @class = "form-control", id = "lang" })
                                </li>
                                <input type="submit" value="Change" class="btn btn-primary" style="margin-left:10px" />
                            </form>
                        }
                    </ul>
                </div>
            </div>
            @if (username == null)
            {
                <div>
                    <a class="fa fa-user mr-3" style="color: darkgreen;" href="@Url.Action("Login", "User")"></a>
                </div>
            } 
            else
            {
                <div>
                    <a class="fa fa-sign-out mr-3" style="color: darkred;" href="@Url.Action("LogOut", "User")"></a>
                </div>
            }
            <div>
                <form style="display: flex;" id="search-form" asp-controller="Home" asp-action="SearchTopic" method="get">
                    <input class="form-control" type="text" required name="searchValue" />
                    <input type="submit" value="Search" class="btn btn-primary" style="margin-left:10px" />
                </form>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - NewsAPI_Implementation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        document.getElementById("language-form").addEventListener("submit", function (event) {
            event.preventDefault();
            var selectedLanguage = document.getElementById("lang").value;
            // Make an AJAX request to the controller action
            var xhr = new XMLHttpRequest();
            xhr.open("POST", "/Home/ChangeLanguage");
            xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
            xhr.onload = function () {
                if (xhr.status === 200) {
                    // Handle the response from the server
                    var data = JSON.parse(xhr.responseText)
                        // Clear the current articles
                    $('.row').empty();
                    // Loop through the new articles and append them to the HTML
                    data.articles.forEach(function(article) {
                        var articleHtml = '<div class="column">' +
                                            '<div class="card">' +
                                            '<img src='+ article.urlToImage +' />' +
                                            '<h3>' + article.title + '</h3>' +
                                            '<p>' + article.description + '</p>' +
                                            '<p>' + article.publishedAt + '</p>' +
                                            '</div>' +
                                         '</div>';
                        $('.row').append(articleHtml);
                    });

                }
                else {
                    // Handle any errors
                }
            };
            xhr.send("Language=" + selectedLanguage);
        });
    });

    function searchTopic() {
        debugger;
        var searchValue = $('#search-input').val()
        $.ajax({
            type: "GET",
            url: "/Home/SearchTopic",
            data: { searchValue: searchValue },
            success: function (data) {
                // Handle the response from the server
            }
        });
    }
</script>